config/routes.rb
BelieversClass::Application.routes.draw do

  resources :administrators

  resources :teachers

  resources :students

  resources :groups do
		
	resources :assignments do
		resources :uploads	
	end

	resources :asistences

  end 
  
  resource :session 

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	validates :description, :presence => true
	validates :duedate, :presence => true

	belongs_to	:group
	has_many	:uploads
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  #before_filter :validateAuth

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @group = Group.find(params[:group_id])
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new
    @group = Group.find(params[:group_id])
    @group.assignments << @assignment

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, :notice => 'Assignment was successfully created.' }
        format.json { render :json => @assignment, :status => :created, :location => @assignment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment.group, :notice => 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @assignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :duedate %><br />
    <%= f.date_select :duedate %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Group</th>
    <th>Duedate</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.id %></td>
    <td><%= assignment.group_id %></td>
    <td><%= assignment.duedate %></td>
    <td><%= assignment.description %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @assignment.id %>
</p>

<p>
  <b>Group:</b>
  <%= @assignment.group_id %>
</p>

<p>
  <b>Duedate:</b>
  <%= @assignment.duedate %>
</p>

<p>
  <b>Description:</b>
  <%= @assignment.description %>
</p>

<%if (session[:type] == 'teacher')%>
  <p>
  <b> Uploads </b>
  <% @assignment.uploads.each do |upload| %>
	<p>
	<%=upload.student.name%> 
	<%=link_to 'Check', group_assignment_upload_path(@group,@assignment,upload)%>
  <%end%>
  <p>
	<%= link_to 'Edit', edit_group_assignment_path(@group,@assignment) %> |
<%elsif (session[:type]=='student')%>
  <%= link_to 'Upload', new_group_assignment_upload_path(@group,@assignment)%>
<%end%>
<%= link_to 'Back', @group %>