config/routes.rb
BelieversClass::Application.routes.draw do

  resources :administrators

  resources :teachers

  resources :students

  resources :groups do
		
	resources :assignments do
		resources :uploads	
	end

	resources :asistences

  end 
  
  resource :session 

end

app/models/group.rb
class Group < ActiveRecord::Base
	validates :level, :presence => true

	has_many 		:students
	belongs_to		:teacher
	has_many		:assignments
	has_many		:asistences
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :validateAuth

  def accesGroup
  end 
  # GET /groups
  # GET /groups.json
  def index
    #@teacher = Teacher.find(params[teacher_id])	
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    #@teacher = Teacher.find(params[:teacher_id])	
    @group = Group.find(params[:id])
    @assignments = @group.assignments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    #@teacher = Teacher.find(params[:teacher_id])
    @group = Group.new
    #@group.teacher_id = @teacher.id
    #@teacher.groups << @group

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    @teacher = Teacher.find(@group.teacher_id)
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, :notice => 'Group was successfully created.' }
        format.json { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    @teacher = Teacher.find(@group.teacher_id)

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, :notice => 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @team = Teacher.find(params[:teacher_id])
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br />
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Teacher</th>
    <th>Level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.id %></td>
    <td><%= group.teacher_id %></td>
    <td><%= group.level %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @group.id %>
</p>

<p>
  <b>Teacher:</b>
  <%= Teacher.find(@group.teacher_id).name %>
</p>

<p>
  <b>Level:</b>
  <%= @group.level %>
</p>

<p>
  <b>Asignments</b>
  <%@group.assignments.each do |asignment|%>
  <p>
  	<%= asignment.description%> <%=asignment.duedate%>
	<%= link_to 'Show', group_assignment_path(@group,asignment) %>
	<% if (session[:type] == 'student') %>
		<%= link_to 'Upload', new_group_assignment_upload_path(@group,asignment)%>
	<% end %>
  <%end%>
<p>
  <% if (session[:type] == 'teacher') %>
	<%= link_to 'New Asignment', new_group_assignment_path(@group) %> |
  <% end%>
<p>

<% if (session[:type] == 'admin') %>
	<%= link_to 'Edit', edit_group_path(@group) %> |
	<%= link_to 'Back', Administrator.find(session[:id]) %>
<% end%>
<% if (session[:type] == 'student') %>
	<%= link_to 'Back', Student.find(session[:id]) %> |
<% end%>
<% if (session[:type] == 'teacher') %>
	<%= link_to 'Asistence', new_group_asistence_path(@group)%> |
	<%= link_to 'New Student', new_student_path %>
	<%= link_to 'Back', Teacher.find(session[:id]) %> |
<% end%>
<% if (session[:id]!=nil) %>
<%= link_to 'Logout', session_path, :method=>:delete%>
<% end %>