config/routes.rb
BelieversClass::Application.routes.draw do

  resources :administrators

  resources :teachers

  resources :students

  resources :groups do
		
	resources :assignments do
		resources :uploads	
	end

	resources :asistences

  end 
  
  resource :session 

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :name, :presence => true
	validates :uname, :presence => true
	validates :uname, :uniqueness => true
	validates :lastname, :presence => true
	validates :password, :presence => true

	has_one	:group
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :isTeacher
  
  def isTeacher
     if(session[:type]==nil)
	redirect_to new_session_path
      	return false;
     #else if(session[:type]!="teacher")
	#redirect_to 
	#return false
     #end 
     else
	return true
     end
  end

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, :notice => 'Teacher was successfully created.' }
        format.json { render :json => @teacher, :status => :created, :location => @teacher }
      else
        format.html { render :action => "new" }
        format.json { render :json => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, :notice => 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Lastname</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.id %></td>
    <td><%= teacher.name %></td>
    <td><%= teacher.lastname %></td>
    <td><%= teacher.phone %></td>
    <td><%= teacher.email %></td>
    <td><%= link_to 'Show', teacher %></td>
    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Destroy', teacher, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teacher', new_teacher_path %>
<%= link_to 'Go back', Administrator.find(session[:id])%>
<% if (session[:id]!=nil) %>
<%= link_to 'Logout', session_path, :method=>:delete%>
<% end %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @teacher.id %>
</p>

<p>
  <b>Name:</b>
  <%= @teacher.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @teacher.lastname %>
</p>

<p>
  <b>Phone:</b>
  <%= @teacher.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @teacher.email %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>