config/routes.rb
BelieversClass::Application.routes.draw do

  resources :administrators

  resources :teachers

  resources :students

  resources :groups do
		
	resources :assignments do
		resources :uploads	
	end

	resources :asistences

  end 
  
  resource :session 

end

app/models/asistence.rb
class Asistence < ActiveRecord::Base
	validates :dateOfClass, :presence => true
	validates :leson, :presence => true		
	
	has_and_belongs_to_many	:students
	belongs_to	:group
end

app/controllers/asistences_controller.rb
class AsistencesController < ApplicationController
  # GET /asistences
  # GET /asistences.json
  def index
    @asistences = Asistence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @asistences }
    end
  end

  # GET /asistences/1
  # GET /asistences/1.json
  def show
    @asistence = Asistence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @asistence }
    end
  end

  # GET /asistences/new
  # GET /asistences/new.json
  def new
    @group = Teacher.find(session[:id]).group
    @asistence = Asistence.new
    @asistence.group = @group
    @group.asistences << @asistence

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @asistence }
    end
  end

  # GET /asistences/1/edit
  def edit
    @asistence = Asistence.find(params[:id])
  end

  # POST /asistences
  # POST /asistences.json
  def create
    @group = Group.find(params[:group_id])
    @asistence = Asistence.new(params[:asistence])

    respond_to do |format|
      if @asistence.save
        format.html { redirect_to @group, :notice => 'Asistence was successfully created.' }
        format.json { render :json => @asistence, :status => :created, :location => @asistence }
      else
        format.html { render :action => "new" }
        format.json { render :json => @asistence.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /asistences/1
  # PUT /asistences/1.json
  def update
    @asistence = Asistence.find(params[:id])
    @group = @asistence.group

    respond_to do |format|
      if @asistence.update_attributes(params[:asistence])
        format.html { redirect_to @group, :notice => 'Asistence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @asistence.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /asistences/1
  # DELETE /asistences/1.json
  def destroy
    @asistence = Asistence.find(params[:id])
    @asistence.destroy

    respond_to do |format|
      format.html { redirect_to asistences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asistences_helper.rb
module AsistencesHelper
end

app/views/asistences/_form.html.erb
<%= form_for([@group,@asistence]) do |f| %>
  <% if @asistence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asistence.errors.count, "error") %> prohibited this asistence from being saved:</h2>

      <ul>
      <% @asistence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :dateOfClass %><br />
    <%= f.date_select :dateOfClass %>
  </div>	
  <div class="field">
    <%= f.label :leson %><br />
    <%= f.text_field :leson %>
  </div>
  <div>
  <% @group.students.each do |student| %>
  <p>
	<%= check_box_tag 'students_ids[]', student%>
	<%= student.name%>
  <% end %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/asistences/edit.html.erb
<h1>Editing asistence</h1>

<%= render 'form' %>

<%= link_to 'Show', group_asistence_path(@group,@asistence) %> |
<%= link_to 'Back', @group %>

app/views/asistences/index.html.erb
<h1>Listing asistences</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Dateofclass</th>
    <th>Leson</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @asistences.each do |asistence| %>
  <tr>
    <td><%= asistence.id %></td>
    <td><%= asistence.dateOfClass %></td>
    <td><%= asistence.leson %></td>
    <td><%= link_to 'Show', asistence %></td>
    <td><%= link_to 'Edit', edit_asistence_path(asistence) %></td>
    <td><%= link_to 'Destroy', asistence, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asistence', new_asistence_path %>

app/views/asistences/new.html.erb
<h1>New asistence</h1>

<%= render 'form' %>

<%= link_to 'Back', @group %>

app/views/asistences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @asistence.id %>
</p>

<p>
  <b>Dateofclass:</b>
  <%= @asistence.dateOfClass %>
</p>

<p>
  <b>Leson:</b>
  <%= @asistence.leson %>
</p>


<%= link_to 'Edit', edit_group_asistence_path(@group,@asistence) %> |
<%= link_to 'Back', @group %>